runtime: nodejs22
env: standard

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "DATABASE_URL"
  FRONTEND_URLS: "FRONTEND_URLS"
  JWT_SECRET: "JWT_SECRET"
  SMTP_HOST: "SMTP_HOST"
  SMTP_PORT: "SMTP_PORT"
  SMTP_SECURE: "SMTP_SECURE"
  SMTP_USER: "SMTP_USER"
  SMTP_PASS: "SMTP_PASS"
  AWS_REGION: "AWS_REGION"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
  AWS_S3_BUCKET: "AWS_S3_BUCKET"

handlers:
  - url: /.*
    script: auto