runtime: nodejs22
env: standard

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "projects/375971071151/secrets/DATABASE_URL/versions/latest"
  FRONTEND_URLS: "projects/375971071151/secrets/FRONTEND_URLS/versions/latest"
  JWT_SECRET: "projects/375971071151/secrets/JWT_SECRET/versions/latest"
  SMTP_HOST: "projects/375971071151/secrets/SMTP_HOST/versions/latest"
  SMTP_PORT: "projects/375971071151/secrets/SMTP_PORT/versions/latest"
  SMTP_SECURE: "projects/375971071151/secrets/SMTP_SECURE/versions/latest"
  SMTP_USER: "projects/375971071151/secrets/SMTP_USER/versions/latest"
  SMTP_PASS: "projects/375971071151/secrets/SMTP_PASS/versions/latest"
  AWS_REGION: "projects/375971071151/secrets/AWS_REGION/versions/latest"
  AWS_ACCESS_KEY_ID: "projects/375971071151/secrets/AWS_ACCESS_KEY_ID/versions/latest"
  AWS_SECRET_ACCESS_KEY: "projects/375971071151/secrets/AWS_SECRET_ACCESS_KEY/versions/latest"
  AWS_S3_BUCKET: "projects/375971071151/secrets/AWS_S3_BUCKET/versions/latest"

handlers:
  - url: /.*
    script: auto
